name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Cache Rust and wasm-pack
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/wasm-pack
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build Wasm
        run: wasm-pack build --target web

      - name: Patch package.json for semantic-release
        run: |
          sed -i 's/"version": "[^"]*"/"version": "0.0.0-semantic-release"/' pkg/package.json

      - name: Install semantic-release plugins
        run: npm install --save-dev semantic-release @semantic-release/git @semantic-release/npm @semantic-release/changelog @semantic-release/github

      - name: Release
        working-directory: ./pkg
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
